### ISSUE TITLE
Application Error During Combat

### ISSUE THREAD

**Issue by ViperDaimao** [BGforgeNet/Fallout2_Restoration_Project#131] opened 2021-12-16 19:00 UTC
### What happened

During combat the application will close and pop up a window with a "memory could not be read" error. It's happened almost every combat for the last 2 days. 

### What you expected to happen

Game does not close and no error appears

### Screenshot
![F2Error](https://user-images.githubusercontent.com/12797364/146431575-decc7bd9-7969-4d43-ab24-f4a37a3f81a5.jpg)

### Savegame
[ApplicationErrorSave.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7729767/ApplicationErrorSave.zip)

**Comment by BlackNightDragon** [comment] 2021-12-17 01:49
I have the same problem. This errors appears to me almost all the time when I fighting with slavers in the Den.

**Comment by ViperDaimao** [comment] 2021-12-17 01:50
Recent changes I made, upgraded to RP v25, added 5th party member brainbot by using mentats, changed GVAR_SAN_FRAN_TANKER from =13 to =0 and GVAR_SAN_FRAN_FUEL_TANK_QST from =2 to =0  to be able to get Dr. Jing to send fuel to the hubologists.

**Comment by burner1024** [comment] 2021-12-17 02:36
see [reporting crashes](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/crash.md)

**Comment by FakelsHub** [comment] 2021-12-17 03:59
99% что проблема в sfall (в последних версиях первые две единицы указывают на, что ошибка возникла в сфалл).
Конфиг пусть загрузит.

**Comment by NovaRain** [comment] 2021-12-17 04:15
> 99% что проблема в sfall (в последних версиях первые две единицы указывают на, то что ошибка возникла в сфалл). Конфиг пусть загрузит.

From the address it seems something related to drugs (right after calling function on drugInfoList data):
```
  11028167: 51                 push        ecx
  11028168: 57                 push        edi
  11028169: 56                 push        esi
  1102816A: B9 08 00 00 00     mov         ecx,8
  1102816F: BF CC 91 51 00     mov         edi,5191CCh // _drugInfoList
  11028174: 8B F3              mov         esi,ebx
  11028176: 8B 07              mov         eax,dword ptr [edi]
  11028178: FF 15 5C 79 09 11  call        dword ptr ds:[1109795Ch]
  1102817E: 85 C0              test        eax,eax
  11028180: 74 10              je          11028192
  11028182: 83 38 00           cmp         dword ptr [eax],0 // crash with eax pointing to 0x1 mem addr
```

**Comment by ViperDaimao** [comment] 2021-12-17 14:15
attaching debug log after reproducing crash
[debug.log](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7735652/debug.log)

**Comment by burner1024** [comment] 2021-12-17 15:17
Also need ddraw.dll, ddraw.ini and the steps. So far I can't reproduce.

**Comment by ViperDaimao** [comment] 2021-12-17 15:56
[ddraw.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/7736282/ddraw.zip)

the crash seems to happen randomly in combat. so I guess the steps would be to enter combat and keep killing people till it crashes. It's usually within 5 mins. I have only been able to complete combat once when it was a quick small encounter.

I do have the addict trait after taking mentats so I wonder if removing that would fix it like NovaRain suggested

**Comment by ViperDaimao** [comment] 2021-12-17 20:01
I rested for a few days and got rid of the addict status and was able to clear out the hubologist compound without a crash.

**Comment by burner1024** [comment] 2021-12-18 09:07
and no crashes in other fights too?

**Comment by ViperDaimao** [comment] 2021-12-18 13:54
Correct. I went from San Fran to New Reno and back accepting every encounter along the way and no crashes. Removing the Addict status seems to have fixed the issue.

**Comment by NovaRain** [comment] 2021-12-18 13:59
Sounds like the queue of withdrawal effect went wrong during the combat, do you by any chance use the party control feature?

**Comment by ViperDaimao** [comment] 2021-12-18 14:05
> 

Is that the add on that allows you to directly control party members? If so, then no, they all act on their own, I just adjust the aggression settings from the combat control menu.

**Comment by FakelsHub** [comment] 2021-12-21 16:59
```
mov  eax, dword ptr [edi];        // eax = drug pid
call fo::funcoffs::item_d_check_addict_;
test eax, eax;                            // Has addiction?
jz   noAddict;                           // No
cmp  dword ptr [eax], 0;          // queue_addict.wait
```
heh strange item_d_check_addict_ does not return any queue
poltergeist broken the code in sfall)))

**Comment by burner1024** [comment] 2022-01-21 07:43
@NovaRain this fixed in sfall now?

**Comment by NovaRain** [comment] 2022-01-21 08:25
Yes.

**Comment by burner1024** [comment] 2022-01-21 09:18
Great, will include in next version!

**Closed by burner1024** 2022-01-21 09:18 UTC
Labels: sfall or engine
