### ISSUE TITLE
Small bug with a caravan in NCR

### ISSUE THREAD

**Issue by egornovivan** [BGforgeNet/Fallout2_Restoration_Project#111] opened 2021-07-31 21:26 UTC
### What happened
Sometimes the trip takes place without a random encounter and the caravan is considered destroyed.
### What you expected to happen
~~Make such trips a successful fulfillment of the escort agreement or~~ delete all trips without random encounters
### Screenshot
https://youtu.be/1DpzyRCTykg?t=283
### Savegame
Saving from fixed edition 3.8.1 (Slightly different from RPUv21)
[SLOT32.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6911821/SLOT32.zip)
Also I've seen this bug before in older RP / Fallout 2 versions

**Comment by egornovivan** [comment] 2021-08-01 00:03
In the video, you can see that upon arrival, the dialogue window opens automatically only for one of the caravan

**Comment by burner1024** [comment] 2021-08-01 15:24
> dialogue window opens automatically only for one of the caravan

Sorry, don't understand what you mean.

Are the rewards proper (monetary) when there's 1 or more encounters?

**Comment by egornovivan** [comment] 2021-08-01 17:23
> Sorry, don't understand what you mean.

Arrival of the Duppo caravan in Redding, a dialog window opens automatically
https://youtu.be/1DpzyRCTykg?t=16
https://youtu.be/1DpzyRCTykg?t=127


Arrival of the Stanwell caravan in Redding, a dialog window NOT opens automatically
https://youtu.be/1DpzyRCTykg?t=242
https://youtu.be/1DpzyRCTykg?t=270

It looks like Stanwell's script is unfinished or broken

**Comment by egornovivan** [comment] 2021-08-02 13:24
> So does it work properly when there's 1 or more encounters?

No, it does not work.  This can be seen in the video.

**Comment by burner1024** [comment] 2021-08-02 13:28
Hard to read text in video, quality is 360p. What's the problem? Just dialog not opening or something else?

**Comment by burner1024** [comment] 2021-08-02 16:03
Also, as I've pretty much never taken caravan, not sure who pays out in Redding for other caravans. Is that the same payout master, or caravan masters themselves?
Prob related https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/69.

**Comment by egornovivan** [comment] 2021-08-02 21:02
> So does it work properly when there's 1 or more encounters?

Yes, everything works correctly

**Comment by burner1024** [comment] 2021-08-02 23:02
This is some bullshit... According to my tests, you can take Stanwell's caravan from NCR to Redding, get payed by the payout master, then wait a few days for Stanwell to appear and get payed again by him.
Then I went with him back to NCR, and there's just no one there. Wait until 11th, get payed by Stanwell personally.

Now I've no idea how'd this worked or even was supposed to work.
Could you test this on 1.02d and 1.02.31 (maybe 2.3.3 too) to see if it's how it always worked, or it's killap's doing?

**Comment by egornovivan** [comment] 2021-08-03 08:15
> get payed by the payout master, then wait a few days for Stanwell to appear and get payed again by him.
> Then I went with him back to NCR, and there's just no one there. Wait until 11th, get payed by Stanwell personally.

Oh shi

> Could you test this on 1.02d and 1.02.31 (maybe 2.3.3 too)

It will take a lot of time, but I'll check it a later.

**Comment by egornovivan** [comment] 2021-08-03 20:37
Saving from GOG version
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6926911/SLOT04.zip)

**Comment by burner1024** [comment] 2021-08-03 22:19
Right. I tried using this save with UPU, and it's pretty much the same.
Then tried loading saves from the other issue in RP, also same. (Not exactly the cleanest test, but close).

So it appears I was too quick to place the blame elsewhere, looks like something's wrong in UPU/RPU. It's quite strange though, as the only change I can think of is #69.

Well, at least it's clear now that payout stand-ins are only supposed to appear once, when corresponding caravan masters are dead.

**Comment by egornovivan** [comment] 2021-08-03 22:50
The reward for the Hal caravan can only be obtained from this NPC, possible it is Hal and not the "payout master"

![изображение](https://user-images.githubusercontent.com/60801856/128095893-22744446-37e7-4e38-8ae0-eea8ea455a87.png)

**Comment by egornovivan** [comment] 2021-08-04 00:45
Saving from GOG+UP
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6927811/SLOT04.zip)

Everything is the same as in GOG, but without loss of FPS

**Comment by burner1024** [comment] 2021-08-04 10:27
No, you're right, this dude pays for Hal in vanilla.

> This is some bullshit... According to my tests, you can take Stanwell's caravan from NCR to Redding, get payed by the payout master, then wait a few days for Stanwell to appear and get payed again by him.
> Then I went with him back to NCR, and there's just no one there. Wait until 11th, get payed by Stanwell personally.

Can you confirm that this works the same way for you in your fixed edition?

**Comment by egornovivan** [comment] 2021-08-04 12:32
> Can you confirm that this works the same way for you in your fixed edition?

I confirm, everything is as you described.  There is no problem with Stanwell.  Problems are created by "payout master"

**Comment by burner1024** [comment] 2021-08-04 13:07
If you want to make a clean save for later tests, save before entering the actual area (redding mine entrance or NCR bazaar), so that broken scripts initialization doesn't screw it up.

**Comment by burner1024** [comment] 2021-08-04 13:42
As for implementation:
1. Need to decide whether Hal's drive is supposed to be repeatable. (Although it's the only one that has a formal quest in  Pip-boy Duppo does says to come back). See #69 and [NMA](https://www.nma-fallout.com/threads/redding-caravans-bug.181693/#post-4247011) for discussion.
2. If yes, then probably this caravan should be made to match the others: Hal himself paying out in Redding, and on Hal's death payout master finishes his duties. (and Duppo no longer says to come back)
3. > delete all trips without random encounters
  Don't know about this, if payment works normally without encounters, why change it?

**Comment by egornovivan** [comment] 2021-08-04 14:40
Saving from GOG+RPU
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6932084/SLOT04.zip)

**Comment by burner1024** [comment] 2021-08-06 15:59
OK, this should fix #110 and #111, as well as allow proper repeatable drives from Duppo (added by killap).
For repeatable drive to work, set
```ini
[ncr]
repeatable_brahmin_drive=1
```
in `mods/upu.ini`
If drive is repeatable and Hal is alive, he will pay out in Redding personally. Otherwise, it will be the other guy.
[caravans.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6946637/caravans.zip)

**Comment by egornovivan** [comment] 2021-08-06 19:23
stuck
[SLOT10.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6947583/SLOT10.zip)
![scr00000](https://user-images.githubusercontent.com/60801856/128561508-a9635ab7-5114-4c75-ae88-2b0b9577a8a9.png)

**Comment by burner1024** [comment] 2021-08-06 19:59
huh.. can you reproduce this reliably, or is it just one-off?

**Comment by egornovivan** [comment] 2021-08-06 20:17
> 
> 
> huh.. can you reproduce this reliably, or is it just one-off?

I have already seen this in the fixed version several times

anomaly, no one is at the encounter (I see for the first time )
[SLOT09.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6947807/SLOT09.zip)
![scr00001](https://user-images.githubusercontent.com/60801856/128566370-f16490bf-3f68-4feb-95a8-b871203eb461.png)

**Comment by burner1024** [comment] 2021-08-06 20:36
what does it say in the display log? Save won't show that.

**Comment by egornovivan** [comment] 2021-08-06 20:53
When entering the encounter, it was 
`You see a man dressed in armor. He looks at you speculatively.`
Then I tried to exit and it re-uploaded to the same encounter with the same message

**Comment by burner1024** [comment] 2021-08-06 21:04
I exited and it goes to redding. I can't reproduce.

**Comment by egornovivan** [comment] 2021-08-06 21:11
>  I can't reproduce.

And i Can't reproduce it either. I should have saved immediately at the first entrance to such an encounter, but I did save only for the second.

**Comment by burner1024** [comment] 2021-08-06 21:24
Don't need to save, just see what it says in display log. I don't think "You see a man dressed in armor." is the first line. Or maybe you missed someone off-screen?
This should fix stuck in cart, I think.
[bhrnddst.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6948022/bhrnddst.int.zip)

**Comment by egornovivan** [comment] 2021-08-06 22:05
> Don't need to save, just see what it says in display log. I don't think "You see a man dressed in armor." is the first line. Or maybe you missed someone off-screen?

Maybe this poisoning triggered the entrance to the encounter?

**Comment by burner1024** [comment] 2021-08-06 22:16
Maybe. Does it break anything?

**Comment by egornovivan** [comment] 2021-08-06 22:22
> Does it break anything?

Nope

**Comment by burner1024** [comment] 2021-08-06 22:24
OK then.., anything else?
You can try killing caravan masters on the road, some brahmin, etc.

**Comment by egornovivan** [comment] 2021-08-06 22:53
> You can try killing caravan masters on the road, some brahmin, etc.

After killing Hal, a grandmaster appeared on the next encounter 
![scr00002](https://user-images.githubusercontent.com/60801856/128578112-7ab7d058-15d1-4384-8d1e-e460e5f56aa5.png)

**Comment by egornovivan** [comment] 2021-08-06 22:56
> anomaly, no one is at the encounter (I see for the first time )

Save reproducing the poisoning trick 
[SLOT07.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6948206/SLOT07.zip)

**Comment by egornovivan** [comment] 2021-08-06 23:16
> After killing Hal, a grandmaster appeared on the next encounter

If we completely destroy our caravan, then upon arrival in Redding we receive $ 1000

**Comment by burner1024** [comment] 2021-08-06 23:54
No idea who's that grand master, guess it's one of the encounters.
I can't reproduce $1k after destroying. Could you show a save (on encounter map, before entering Redding)?

**Comment by egornovivan** [comment] 2021-08-07 00:27
> Could you show a save (on encounter map, before entering Redding)?

[grandmaster_and_1k.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6948335/grandmaster_and_1k.zip)

**Comment by burner1024** [comment] 2021-08-07 00:48
Grand Master is apparently just a normal random encounter https://fallout.fandom.com/wiki/Fallout_2_random_encounters

Found the problem with payment, it also indicates deeper issues (`scdrvpay: caravan_brahmin_left: -2`), probably somewhere brahmin counter takes into account non-caravan brahmin or something, and when killing all, it goes negative. For now, I added a dirty fix.
[update.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6948356/update.zip)

**Comment by egornovivan** [comment] 2021-08-07 00:53
> Grand Master is apparently just a normal random

He has a green outline, like an ally

**Comment by burner1024** [comment] 2021-08-07 01:12
![Captura de pantalla de 2021-08-07 08-06-44](https://user-images.githubusercontent.com/1279852/128583271-f2764cd8-7f9f-4188-94ec-ca51e2bde882.png)

I wonder if 23 years later is late enough... This is from 1.02d sources.
[schal.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6948380/schal.zip)
This should get rid of the grand master (you'll need to kill Hal again).

**Comment by egornovivan** [comment] 2021-08-07 09:27
>  I added a dirty fix.

Sometimes the bug is reproduced with all updates

**Comment by burner1024** [comment] 2021-08-07 09:58
Share debug.log if you manage to see it again.

**Comment by egornovivan** [comment] 2021-08-07 10:33
> Share debug.log if you manage to see it again.

[log_1k.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6948951/log_1k.zip)
[save_1k.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6948952/save_1k.zip)

**Comment by burner1024** [comment] 2021-08-07 11:25
You missed one. 
![Captura de pantalla de 2021-08-07 17-55-26](https://user-images.githubusercontent.com/1279852/128598571-017d0de7-a53f-450e-96ce-a5552d54db01.png)

That triggered yet another bug, when last brahmin wouldn't show on the following maps.
[bhrnddst.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6948995/bhrnddst.int.zip)

**Comment by egornovivan** [comment] 2021-08-07 11:27
> You missed one.

I did it on purpose )

**Comment by burner1024** [comment] 2021-08-07 11:36
Leaving one brahmin is not completely destroying. Paying 1k in case one brahmin left is normal behaviour.

**Comment by egornovivan** [comment] 2021-08-07 11:41
stuck
[stuck_log.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6949009/stuck_log.zip)
[stuck_save.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6949010/stuck_save.zip)

**Comment by burner1024** [comment] 2021-08-07 15:10
Sometimes guards would stuck too. Caravans were created with some empty space inside. I added more blocking hexes.
[bhrnddst.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6949298/bhrnddst.int.zip)

**Comment by egornovivan** [comment] 2021-08-07 18:17
I told Hal that I would not go with him, and he was all gone. No longer appears when taking a quest from Duppo
[hal_offended_save.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6949567/hal_offended_save.zip)

**Comment by burner1024** [comment] 2021-08-07 18:38
you mean he disappeared right after conversation?

**Comment by egornovivan** [comment] 2021-08-07 18:45
first I told him "no", then I left the city, and now he does not appear when taking the quest from Duppo

**Comment by burner1024** [comment] 2021-08-07 18:56
Ok... this one should allow him to reappear if the quest is taken again.
I also changed the dialog so that you can still go on the drive if you said no first but then talked to him again right away.
[schal.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6949600/schal.int.zip)

**Comment by egornovivan** [comment] 2021-08-07 21:39
Reproducible anomalies with empty encounter and no poisoning
[anomaly_log.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6949860/anomaly_log.zip)
[anomaly_save.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6949861/anomaly_save.zip)

**Comment by egornovivan** [comment] 2021-08-07 23:49
After completing the quest, Duppo does not give access to the casino (I don’t remember how it worked before)
[SLOT16.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6950029/SLOT16.zip)

**Comment by burner1024** [comment] 2021-08-08 19:38
Duppo thing is how it always worked, I think, see [walkthrough](https://lemmings19.github.io/fallout-2-walkthrough/). It does look somewhat strange, though.

On empty caravans: I think it's caused by script setting area position on worldmap, but checking player position instead (apparently they are stored independently?). Some old info from Darek [here](https://nma-fallout.com/threads/fallout-2-restoration-project-2-1-2b-unofficial-expansion.193435/page-41#post-3845174).
If I'm correct, it means that many cases the encounters were shifted by one or something like that - when loading the area, you'd draw an encounter from the table corresponding to the previous worldmap position, rather than current.

It touches other caravans, too, so it's time to test all over again...

Overall, this code is horrible and should be burnt with fire.

[bhrnddst.int.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6951359/bhrnddst.int.zip)

**Comment by egornovivan** [comment] 2021-08-08 21:43
> bhrnddst.int.zip

Hmm. Through poisoning now does not seem to be reproduced

**Comment by burner1024** [comment] 2021-08-08 22:46
What alarm clock? Do you mean possibility to sleep?

**Comment by egornovivan** [comment] 2021-08-08 23:29
>  Do you mean possibility to sleep?

Yes, but it doesn't seem to break anything

____
In the Hal quest, if you escape from the battle, then Hal appears in Redding and pays$1000(it also doesn't seem to break anything)

**Comment by burner1024** [comment] 2021-08-09 00:15
> Yes, but it doesn't seem to break anything

I can't reproduce that.

> In the Hal quest, if you escape from the battle, then Hal appears in Redding and pays$1000(it also doesn't seem to break anything)

Added a fix for this.

[1.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/6951674/1.zip)

**Closed** 2021-08-09 17:26 UTC

**Comment by burner1024** [comment] 2021-08-09 17:33
Enough changes for one issue, if something else comes, it can be handled separately.
