### ISSUE TITLE
Crippled Frank Horrigan vacillates between weapons

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#206] opened 2023-06-03 11:13 UTC
### What happened

1. Eat the cookie
2. Enter combat mode
3. Rush over to Frank Horrigan
4. As soon as he’s done hitting you, **cripple _both_ of his arms** (don’t skip this step!)
5. Stand immediately in front of him

My character is a Slayer, so crippling his arms is easy.

At first this is actually kind of funny (‘Look like I’m gonna need my knife for this situation. Wait, no, maybe I can still fire my gun! Agh, but it feels so heavy now, I’ll just stick to the knife… after I check my gun again. Yeah, too heavy. Okay, maybe I’ll go with the knife… wait, did I hold my gun properly? Let me check that one more time…’), but after a while it becomes tiresome.

It looks like a game‐breaking bug at first because of how long he vacillates, but it isn’t. He just takes a long time and it’s annoying.

### What you expected to happen

All of the other NPCs switch to unarmed when both of their arms are crippled. Logically. Frank Horrigan should do the same. On the other hand (heh), I noticed that when the Chosen One is standing **away** from Frank Horrigan while his arms are crippled, he simply stands there absent‐mindedly.

### Screenshot

You can’t really demonstrate this through a screenshot, but whatever.

![scr00001](https://github.com/BGforgeNet/Fallout2_Restoration_Project/assets/51846125/6f4de808-c217-426f-bd41-c382b4bf7a81)

### Savegame

[Harry Callahan.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/11642433/Harry.Callahan.zip)

**Comment by burner1024** [comment] 2024-02-25 15:11
1. I can't reproduce multi-weapon switching in v28. Maybe fixed by later sfall.
2. I can reproduce standing idly in some cases. Loading second save and just backing off is enough.

There's nothing interesting in the log, though, and no special targeting in the script. It seems that's just what AI decides to do.
@NovaRain you have any idea what's going on here?

**Comment by NovaRain** [comment] 2024-02-26 02:26
In the second save (SLOT09), he has both arms, right leg, and eyes crippled, so he has the error log from `ai_danger_source()`:
https://github.com/alexbatalov/fallout2-re/blob/main/src/game/combatai.c#L1530
because `combat_check_bad_shot()` doesn't return OK:
https://github.com/alexbatalov/fallout2-re/blob/main/src/game/combat.c#L5523

If I remove the gun from his hand (e.g. call `unwield_inven()` on him), he will start chasing and punching player.

**Comment by burner1024** [comment] 2024-02-26 06:59
OK let's just unequip both.
It should probably be fixed in CE anyway.

**Closed** 2024-02-26 07:00 UTC
